In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input/playground-series-s5e12/train.csv'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
df=pd.read_csv('/kaggle/input/playground-series-s5e12/train.csv')

In [3]:
df.head()

,id,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
0,0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,...,Female,Hispanic,Highschool,Lower-Middle,Current,Employed,0,0,0,1.0
1,1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
2,2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,...,Male,Hispanic,Highschool,Lower-Middle,Never,Retired,0,0,0,0.0
3,3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,...,Female,White,Highschool,Lower-Middle,Current,Employed,0,1,0,1.0
4,4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,...,Male,White,Highschool,Upper-Middle,Never,Retired,0,1,0,1.0

In [4]:
df.shape

(700000, 26)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 26 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   id                                  700000 non-null  int64
 1   age                                 700000 non-null  int64
 2   alcohol_consumption_per_week        700000 non-null  int64
 3   physical_activity_minutes_per_week  700000 non-null  int64
 4   diet_score                          700000 non-null  float64
 5   sleep_hours_per_day                 700000 non-null  float64
 6   screen_time_hours_per_day           700000 non-null  float64
 7   bmi                                 700000 non-null  float64
 8   waist_to_hip_ratio                  700000 non-null  float64
 9   systolic_bp                         700000 non-null  int64
 10  diastolic_bp                        700000 non-null  int64
 11  heart_rate                          700000 non-null  int64
 12  cholesterol_total                   700000 non-null  int64
 13  hdl_cholesterol                     700000 non-null  int64
 14  ldl_cholesterol                     700000 non-null  int64
 15  triglycerides                       700000 non-null  int64
 16  gender                              700000 non-null  object
 17  ethnicity                           700000 non-null  object
 18  education_level                     700000 non-null  object
 19  income_level                        700000 non-null  object
 20  smoking_status                      700000 non-null  object
 21  employment_status                   700000 non-null  object
 22  family_history_diabetes             700000 non-null  int64
 23  hypertension_history                700000 non-null  int64
 24  cardiovascular_history              700000 non-null  int64
 25  diagnosed_diabetes                  700000 non-null  float64
dtypes: float64(6), int64(14), object(6)
memory usage: 138.9+ MB

In [6]:
df.isna().sum()

id                                    0
age                                   0
alcohol_consumption_per_week          0
physical_activity_minutes_per_week    0
diet_score                            0
sleep_hours_per_day                   0
screen_time_hours_per_day             0
bmi                                   0
waist_to_hip_ratio                    0
systolic_bp                           0
diastolic_bp                          0
heart_rate                            0
cholesterol_total                     0
hdl_cholesterol                       0
ldl_cholesterol                       0
triglycerides                         0
gender                                0
ethnicity                             0
education_level                       0
income_level                          0
smoking_status                        0
employment_status                     0
family_history_diabetes               0
hypertension_history                  0
cardiovascular_history                0
diagnosed_diabetes                    0
dtype: int64

In [7]:
df = df.drop(['id'], axis=1)

In [8]:
df.head()

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,diastolic_bp,...,gender,ethnicity,education_level,income_level,smoking_status,employment_status,family_history_diabetes,hypertension_history,cardiovascular_history,diagnosed_diabetes
0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,70,...,Female,Hispanic,Highschool,Lower-Middle,Current,Employed,0,0,0,1.0
1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,77,...,Female,White,Highschool,Upper-Middle,Never,Employed,0,0,0,1.0
2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,89,...,Male,Hispanic,Highschool,Lower-Middle,Never,Retired,0,0,0,0.0
3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,69,...,Female,White,Highschool,Lower-Middle,Current,Employed,0,1,0,1.0
4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,60,...,Male,White,Highschool,Upper-Middle,Never,Retired,0,1,0,1.0

In [9]:
cat_cols = [
    'gender',
    'ethnicity',
    'smoking_status',
    'employment_status'
]
df = pd.get_dummies(
    df,
    columns=cat_cols,
    drop_first=True   # avoids dummy variable trap
)

In [10]:
df.head()

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,diastolic_bp,...,gender_Other,ethnicity_Black,ethnicity_Hispanic,ethnicity_Other,ethnicity_White,smoking_status_Former,smoking_status_Never,employment_status_Retired,employment_status_Student,employment_status_Unemployed
0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,70,...,False,False,True,False,False,False,False,False,False,False
1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,77,...,False,False,False,False,True,False,True,False,False,False
2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,89,...,False,False,True,False,False,False,True,True,False,False
3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,69,...,False,False,False,False,True,False,False,False,False,False
4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,60,...,False,False,False,False,True,False,True,True,False,False

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 32 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 700000 non-null  int64
 1   alcohol_consumption_per_week        700000 non-null  int64
 2   physical_activity_minutes_per_week  700000 non-null  int64
 3   diet_score                          700000 non-null  float64
 4   sleep_hours_per_day                 700000 non-null  float64
 5   screen_time_hours_per_day           700000 non-null  float64
 6   bmi                                 700000 non-null  float64
 7   waist_to_hip_ratio                  700000 non-null  float64
 8   systolic_bp                         700000 non-null  int64
 9   diastolic_bp                        700000 non-null  int64
 10  heart_rate                          700000 non-null  int64
 11  cholesterol_total                   700000 non-null  int64
 12  hdl_cholesterol                     700000 non-null  int64
 13  ldl_cholesterol                     700000 non-null  int64
 14  triglycerides                       700000 non-null  int64
 15  education_level                     700000 non-null  object
 16  income_level                        700000 non-null  object
 17  family_history_diabetes             700000 non-null  int64
 18  hypertension_history                700000 non-null  int64
 19  cardiovascular_history              700000 non-null  int64
 20  diagnosed_diabetes                  700000 non-null  float64
 21  gender_Male                         700000 non-null  bool
 22  gender_Other                        700000 non-null  bool
 23  ethnicity_Black                     700000 non-null  bool
 24  ethnicity_Hispanic                  700000 non-null  bool
 25  ethnicity_Other                     700000 non-null  bool
 26  ethnicity_White                     700000 non-null  bool
 27  smoking_status_Former               700000 non-null  bool
 28  smoking_status_Never                700000 non-null  bool
 29  employment_status_Retired           700000 non-null  bool
 30  employment_status_Student           700000 non-null  bool
 31  employment_status_Unemployed        700000 non-null  bool
dtypes: bool(11), float64(6), int64(13), object(2)
memory usage: 119.5+ MB

In [12]:
df['bp_category'] = (
    (df['systolic_bp'] >= 140) | (df['diastolic_bp'] >= 90)
).astype(int)

In [13]:
df.head()

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,diastolic_bp,...,ethnicity_Black,ethnicity_Hispanic,ethnicity_Other,ethnicity_White,smoking_status_Former,smoking_status_Never,employment_status_Retired,employment_status_Student,employment_status_Unemployed,bp_category
0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,70,...,False,True,False,False,False,False,False,False,False,0
1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,77,...,False,False,False,True,False,True,False,False,False,0
2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,89,...,False,True,False,False,False,True,True,False,False,0
3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,69,...,False,False,False,True,False,False,False,False,False,0
4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,60,...,False,False,False,True,False,True,True,False,False,0

In [14]:
df['obese'] = (df['bmi'] >= 30).astype(int)

In [15]:
df['sleep_risk'] = (
    (df['sleep_hours_per_day'] < 6) | 
    (df['sleep_hours_per_day'] > 9)
).astype(int)

In [16]:
df['cholesterol_ratio'] = df['ldl_cholesterol'] / df['hdl_cholesterol']

In [17]:
df.head()

,age,alcohol_consumption_per_week,physical_activity_minutes_per_week,diet_score,sleep_hours_per_day,screen_time_hours_per_day,bmi,waist_to_hip_ratio,systolic_bp,diastolic_bp,...,ethnicity_White,smoking_status_Former,smoking_status_Never,employment_status_Retired,employment_status_Student,employment_status_Unemployed,bp_category,obese,sleep_risk,cholesterol_ratio
0,31,1,45,7.7,6.8,6.1,33.4,0.93,112,70,...,False,False,False,False,False,False,0,1,0,1.965517
1,50,2,73,5.7,6.5,5.8,23.8,0.83,120,77,...,True,False,True,False,False,False,0,0,0,2.420000
2,32,3,158,8.5,7.4,9.1,24.1,0.83,95,89,...,False,False,True,True,False,False,0,0,0,1.932203
3,54,3,77,4.6,7.0,9.2,26.6,0.83,121,69,...,True,False,False,False,False,False,0,0,0,1.574074
4,54,1,55,5.7,6.2,5.1,28.8,0.90,108,60,...,True,False,True,True,False,False,0,0,0,2.673469

In [18]:
df['activity_level'] = pd.cut(
    df['physical_activity_minutes_per_week'],
    bins=[-1, 149, 300, np.inf],
    labels=[0, 1, 2]
).astype(int)

In [19]:
df['lifestyle_risk'] = (
    (df.filter(like='smoking_status_').sum(axis=1) > 0).astype(int) +
    (df['alcohol_consumption_per_week'] > 14).astype(int) +
    (df['screen_time_hours_per_day'] > 6).astype(int) +
    (df['activity_level'] == 0).astype(int)
)

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 38 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 700000 non-null  int64
 1   alcohol_consumption_per_week        700000 non-null  int64
 2   physical_activity_minutes_per_week  700000 non-null  int64
 3   diet_score                          700000 non-null  float64
 4   sleep_hours_per_day                 700000 non-null  float64
 5   screen_time_hours_per_day           700000 non-null  float64
 6   bmi                                 700000 non-null  float64
 7   waist_to_hip_ratio                  700000 non-null  float64
 8   systolic_bp                         700000 non-null  int64
 9   diastolic_bp                        700000 non-null  int64
 10  heart_rate                          700000 non-null  int64
 11  cholesterol_total                   700000 non-null  int64
 12  hdl_cholesterol                     700000 non-null  int64
 13  ldl_cholesterol                     700000 non-null  int64
 14  triglycerides                       700000 non-null  int64
 15  education_level                     700000 non-null  object
 16  income_level                        700000 non-null  object
 17  family_history_diabetes             700000 non-null  int64
 18  hypertension_history                700000 non-null  int64
 19  cardiovascular_history              700000 non-null  int64
 20  diagnosed_diabetes                  700000 non-null  float64
 21  gender_Male                         700000 non-null  bool
 22  gender_Other                        700000 non-null  bool
 23  ethnicity_Black                     700000 non-null  bool
 24  ethnicity_Hispanic                  700000 non-null  bool
 25  ethnicity_Other                     700000 non-null  bool
 26  ethnicity_White                     700000 non-null  bool
 27  smoking_status_Former               700000 non-null  bool
 28  smoking_status_Never                700000 non-null  bool
 29  employment_status_Retired           700000 non-null  bool
 30  employment_status_Student           700000 non-null  bool
 31  employment_status_Unemployed        700000 non-null  bool
 32  bp_category                         700000 non-null  int64
 33  obese                               700000 non-null  int64
 34  sleep_risk                          700000 non-null  int64
 35  cholesterol_ratio                   700000 non-null  float64
 36  activity_level                      700000 non-null  int64
 37  lifestyle_risk                      700000 non-null  int64
dtypes: bool(11), float64(7), int64(18), object(2)
memory usage: 151.5+ MB

In [21]:
df['metabolic_risk'] = (
    (df['bmi'] >= 30).astype(int) +
    (df['bp_category'] == 1).astype(int) +
    (df['cholesterol_ratio'] > 5).astype(int) +
    (df['triglycerides'] > 150).astype(int)
)

In [22]:
df[
    ['bp_category', 'cholesterol_ratio', 'obese',
     'activity_level', 'sleep_risk',
     'lifestyle_risk', 'metabolic_risk']
].head()

,bp_category,cholesterol_ratio,obese,activity_level,sleep_risk,lifestyle_risk,metabolic_risk
0,0,1.965517,1,0,0,2,1
1,0,2.420000,0,0,0,2,0
2,0,1.932203,0,1,0,2,0
3,0,1.574074,0,0,0,2,0
4,0,2.673469,0,0,0,2,0

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 39 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 700000 non-null  int64
 1   alcohol_consumption_per_week        700000 non-null  int64
 2   physical_activity_minutes_per_week  700000 non-null  int64
 3   diet_score                          700000 non-null  float64
 4   sleep_hours_per_day                 700000 non-null  float64
 5   screen_time_hours_per_day           700000 non-null  float64
 6   bmi                                 700000 non-null  float64
 7   waist_to_hip_ratio                  700000 non-null  float64
 8   systolic_bp                         700000 non-null  int64
 9   diastolic_bp                        700000 non-null  int64
 10  heart_rate                          700000 non-null  int64
 11  cholesterol_total                   700000 non-null  int64
 12  hdl_cholesterol                     700000 non-null  int64
 13  ldl_cholesterol                     700000 non-null  int64
 14  triglycerides                       700000 non-null  int64
 15  education_level                     700000 non-null  object
 16  income_level                        700000 non-null  object
 17  family_history_diabetes             700000 non-null  int64
 18  hypertension_history                700000 non-null  int64
 19  cardiovascular_history              700000 non-null  int64
 20  diagnosed_diabetes                  700000 non-null  float64
 21  gender_Male                         700000 non-null  bool
 22  gender_Other                        700000 non-null  bool
 23  ethnicity_Black                     700000 non-null  bool
 24  ethnicity_Hispanic                  700000 non-null  bool
 25  ethnicity_Other                     700000 non-null  bool
 26  ethnicity_White                     700000 non-null  bool
 27  smoking_status_Former               700000 non-null  bool
 28  smoking_status_Never                700000 non-null  bool
 29  employment_status_Retired           700000 non-null  bool
 30  employment_status_Student           700000 non-null  bool
 31  employment_status_Unemployed        700000 non-null  bool
 32  bp_category                         700000 non-null  int64
 33  obese                               700000 non-null  int64
 34  sleep_risk                          700000 non-null  int64
 35  cholesterol_ratio                   700000 non-null  float64
 36  activity_level                      700000 non-null  int64
 37  lifestyle_risk                      700000 non-null  int64
 38  metabolic_risk                      700000 non-null  int64
dtypes: bool(11), float64(7), int64(19), object(2)
memory usage: 156.9+ MB

In [24]:
education_map = {
    'No schooling': 0,
    'High school': 1,
    'Graduate': 2,
    'Postgraduate': 3
}

income_map = {
    'Low': 0,
    'Medium': 1,
    'High': 2
}

df['education_level'] = df['education_level'].map(education_map)
df['income_level'] = df['income_level'].map(income_map)

In [25]:
df.select_dtypes(include='object').columns

Index([], dtype='object')

In [26]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700000 entries, 0 to 699999
Data columns (total 39 columns):
 #   Column                              Non-Null Count   Dtype
---  ------                              --------------   -----
 0   age                                 700000 non-null  int64
 1   alcohol_consumption_per_week        700000 non-null  int64
 2   physical_activity_minutes_per_week  700000 non-null  int64
 3   diet_score                          700000 non-null  float64
 4   sleep_hours_per_day                 700000 non-null  float64
 5   screen_time_hours_per_day           700000 non-null  float64
 6   bmi                                 700000 non-null  float64
 7   waist_to_hip_ratio                  700000 non-null  float64
 8   systolic_bp                         700000 non-null  int64
 9   diastolic_bp                        700000 non-null  int64
 10  heart_rate                          700000 non-null  int64
 11  cholesterol_total                   700000 non-null  int64
 12  hdl_cholesterol                     700000 non-null  int64
 13  ldl_cholesterol                     700000 non-null  int64
 14  triglycerides                       700000 non-null  int64
 15  education_level                     340910 non-null  float64
 16  income_level                        103037 non-null  float64
 17  family_history_diabetes             700000 non-null  int64
 18  hypertension_history                700000 non-null  int64
 19  cardiovascular_history              700000 non-null  int64
 20  diagnosed_diabetes                  700000 non-null  float64
 21  gender_Male                         700000 non-null  int64
 22  gender_Other                        700000 non-null  int64
 23  ethnicity_Black                     700000 non-null  int64
 24  ethnicity_Hispanic                  700000 non-null  int64
 25  ethnicity_Other                     700000 non-null  int64
 26  ethnicity_White                     700000 non-null  int64
 27  smoking_status_Former               700000 non-null  int64
 28  smoking_status_Never                700000 non-null  int64
 29  employment_status_Retired           700000 non-null  int64
 30  employment_status_Student           700000 non-null  int64
 31  employment_status_Unemployed        700000 non-null  int64
 32  bp_category                         700000 non-null  int64
 33  obese                               700000 non-null  int64
 34  sleep_risk                          700000 non-null  int64
 35  cholesterol_ratio                   700000 non-null  float64
 36  activity_level                      700000 non-null  int64
 37  lifestyle_risk                      700000 non-null  int64
 38  metabolic_risk                      700000 non-null  int64
dtypes: float64(9), int64(30)
memory usage: 208.3 MB

In [28]:
df['education_level'] = df['education_level'].fillna(df['education_level'].median())
df['income_level'] = df['income_level'].fillna(df['income_level'].median())

In [29]:
df.isna().sum()

age                                   0
alcohol_consumption_per_week          0
physical_activity_minutes_per_week    0
diet_score                            0
sleep_hours_per_day                   0
screen_time_hours_per_day             0
bmi                                   0
waist_to_hip_ratio                    0
systolic_bp                           0
diastolic_bp                          0
heart_rate                            0
cholesterol_total                     0
hdl_cholesterol                       0
ldl_cholesterol                       0
triglycerides                         0
education_level                       0
income_level                          0
family_history_diabetes               0
hypertension_history                  0
cardiovascular_history                0
diagnosed_diabetes                    0
gender_Male                           0
gender_Other                          0
ethnicity_Black                       0
ethnicity_Hispanic                    0
ethnicity_Other                       0
ethnicity_White                       0
smoking_status_Former                 0
smoking_status_Never                  0
employment_status_Retired             0
employment_status_Student             0
employment_status_Unemployed          0
bp_category                           0
obese                                 0
sleep_risk                            0
cholesterol_ratio                     0
activity_level                        0
lifestyle_risk                        0
metabolic_risk                        0
dtype: int64

In [30]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from xgboost import XGBClassifier

In [31]:
X = df.drop(columns='diagnosed_diabetes')
y = df['diagnosed_diabetes'].astype(int)

In [32]:
X_train, X_val, y_train, y_val = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [33]:
xgb = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    eval_metric='auc',
    random_state=42,
    n_jobs=-1
)

In [34]:
xgb.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1,
              num_parallel_tree=None, random_state=42, ...)

In [35]:
val_prob = xgb.predict_proba(X_val)[:, 1]
roc = roc_auc_score(y_val, val_prob)

print("Validation ROC-AUC:", roc)

Validation ROC-AUC: 0.7222732370811193

In [36]:
xgb_final = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    objective='binary:logistic',
    eval_metric='auc',
    random_state=42,
    n_jobs=-1
)

xgb_final.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.05, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=6, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=300, n_jobs=-1,
              num_parallel_tree=None, random_state=42, ...)

In [37]:
test_df  = pd.read_csv('/kaggle/input/playground-series-s5e12/test.csv')

In [38]:
test_ids = test_df['id']

In [39]:
X_test = test_df.drop(columns='id')

In [40]:
y = df['diagnosed_diabetes']
X = df.drop('diagnosed_diabetes', axis=1)

In [41]:
test_df.columns

Index(['id', 'age', 'alcohol_consumption_per_week',
       'physical_activity_minutes_per_week', 'diet_score',
       'sleep_hours_per_day', 'screen_time_hours_per_day', 'bmi',
       'waist_to_hip_ratio', 'systolic_bp', 'diastolic_bp', 'heart_rate',
       'cholesterol_total', 'hdl_cholesterol', 'ldl_cholesterol',
       'triglycerides', 'gender', 'ethnicity', 'education_level',
       'income_level', 'smoking_status', 'employment_status',
       'family_history_diabetes', 'hypertension_history',
       'cardiovascular_history'],
      dtype='object')

In [42]:
test_ids = test_df['id']
X_test = test_df.drop('id', axis=1)

In [43]:
y = df['diagnosed_diabetes']
X = df.drop('diagnosed_diabetes', axis=1)

In [44]:
X.select_dtypes(include='object').columns

Index([], dtype='object')

In [45]:
from xgboost import XGBClassifier

xgb_final = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    eval_metric='logloss',
    random_state=42
)

xgb_final.fit(X, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [46]:
test_ids = test_df['id']
X_test = test_df.drop('id', axis=1)

In [47]:
X_test.shape[1] == X.shape[1]

False

In [48]:
set(X.columns) - set(X_test.columns)

{'activity_level',
 'bp_category',
 'cholesterol_ratio',
 'employment_status_Retired',
 'employment_status_Student',
 'employment_status_Unemployed',
 'ethnicity_Black',
 'ethnicity_Hispanic',
 'ethnicity_Other',
 'ethnicity_White',
 'gender_Male',
 'gender_Other',
 'lifestyle_risk',
 'metabolic_risk',
 'obese',
 'sleep_risk',
 'smoking_status_Former',
 'smoking_status_Never'}

In [49]:
X_test = X_test.reindex(columns=X.columns, fill_value=0)

In [50]:
X_test.shape[1] == X.shape[1]

True

In [51]:
full_df = pd.concat([X, X_test], axis=0)

In [52]:
full_df = pd.get_dummies(
    full_df,
    columns=['education_level', 'income_level'],
    drop_first=True
)

In [53]:
bool_cols = full_df.select_dtypes(include='bool').columns
full_df[bool_cols] = full_df[bool_cols].astype(int)

In [54]:
X = full_df.iloc[:len(y)]
X_test = full_df.iloc[len(y):]

In [55]:
X.select_dtypes(include='object').columns
X_test.select_dtypes(include='object').columns

Index([], dtype='object')

In [56]:
y = df['diagnosed_diabetes']

df = df.drop('diagnosed_diabetes', axis=1)

test_ids = test_df['id']
test_df = test_df.drop('id', axis=1)

In [57]:
full_df = pd.concat([df, test_df], axis=0)

In [58]:
full_df = pd.get_dummies(
    full_df,
    columns=['education_level', 'income_level'],
    drop_first=True
)

In [59]:
bool_cols = full_df.select_dtypes(include='bool').columns
full_df[bool_cols] = full_df[bool_cols].astype(int)

In [60]:
X = full_df.iloc[:len(y)]
X_test = full_df.iloc[len(y):]

In [61]:
print(X.shape, X_test.shape)
print(X_test.shape[1] == X.shape[1])
print(X.select_dtypes(include='object').columns)
print(X_test.select_dtypes(include='object').columns)

(700000, 51) (300000, 51)
True
Index(['gender', 'ethnicity', 'smoking_status', 'employment_status'], dtype='object')
Index(['gender', 'ethnicity', 'smoking_status', 'employment_status'], dtype='object')

In [62]:
cat_cols = X.select_dtypes(include="object").columns
cat_cols

Index(['gender', 'ethnicity', 'smoking_status', 'employment_status'], dtype='object')

In [63]:
X_encoded = pd.get_dummies(X, columns=cat_cols, drop_first=True)

In [64]:
xgb_final.fit(X_encoded, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='logloss',
              feature_types=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=0.05, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=6,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=300,
              n_jobs=None, num_parallel_tree=None, random_state=42, ...)

In [65]:
X_encoded.columns[X_encoded.columns.duplicated()]

Index([], dtype='object')

In [66]:


X_encoded = X_encoded.loc[:, ~X_encoded.columns.duplicated()]

In [67]:
import pandas as pd

X_test_encoded = pd.get_dummies(X_test) 

X_test_encoded = X_test_encoded.loc[:, ~X_test_encoded.columns.duplicated()]

In [68]:
X_test_encoded = X_test_encoded.reindex(
    columns=X_encoded.columns,
    fill_value=0
)

In [69]:
print(X_encoded.shape)
print(X_test_encoded.shape)
print(X_encoded.columns.equals(X_test_encoded.columns))

(700000, 47)
(300000, 47)
True

In [70]:
test_prob = xgb_final.predict_proba(X_test_encoded)[:, 1]

In [71]:
submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

In [72]:
submission = pd.DataFrame({
    "diagnosed_diabetes": test_prob
})

In [73]:
submission.to_csv("submission.csv", index=False)

In [74]:
submission.head()
submission.describe()

       diagnosed_diabetes
count       300000.000000
mean             0.608131
std              0.176676
min              0.068154
25%              0.479833
50%              0.608043
75%              0.737717
max              0.988659

In [75]:

submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

submission.to_csv("submission.csv", index=False)

In [76]:
from sklearn.metrics import roc_auc_score

train_pred = xgb_final.predict_proba(X_encoded)[:, 1]
roc_auc_score(y, train_pred)

0.7331644231930776

In [77]:

submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

submission.to_csv("submission.csv", index=False)

In [78]:
submission.head()

       id  diagnosed_diabetes
0  700000            0.532900
1  700001            0.629233
2  700002            0.733112
3  700003            0.443071
4  700004            0.888926

In [79]:
submission.to_csv("submission.csv", index=False)

In [80]:
import os
os.listdir()

['__notebook__.ipynb', 'submission.csv']

In [81]:
from sklearn.model_selection import train_test_split

X_tr, X_val, y_tr, y_val = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [82]:
xgb = XGBClassifier(
    n_estimators=1000,
    max_depth=5,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,
    eval_metric="auc",
    early_stopping_rounds=50,
    random_state=42,
    n_jobs=-1
)

xgb.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    verbose=False
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=50,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=-1,
              num_parallel_tree=None, random_state=42, ...)

In [83]:
xgb.best_iteration

996

In [84]:
best_n = xgb.best_iteration + 1

In [85]:
xgb_final = XGBClassifier(
    n_estimators=best_n,
    max_depth=5,
    learning_rate=0.03,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=5,
    eval_metric="auc",
    random_state=42,
    n_jobs=-1
)

xgb_final.fit(X_encoded, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.8, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=5, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=997, n_jobs=-1,
              num_parallel_tree=None, random_state=42, ...)

In [86]:
test_prob = xgb_final.predict_proba(X_test_encoded)[:, 1]

In [87]:
submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

In [88]:
submission.head()

       id  diagnosed_diabetes
0  700000            0.553518
1  700001            0.694977
2  700002            0.777020
3  700003            0.430060
4  700004            0.922165

In [89]:
submission.to_csv("submission.csv", index=False)

In [90]:
import os
os.listdir()

['__notebook__.ipynb', 'submission.csv']

In [91]:
neg = (y == 0).sum()
pos = (y == 1).sum()
scale_pos_weight = neg / pos
scale_pos_weight

0.6043749011590462

In [92]:
xgb = XGBClassifier(
    n_estimators=1000,
    max_depth=4,              # slightly smaller
    learning_rate=0.03,
    subsample=0.85,
    colsample_bytree=0.85,
    min_child_weight=8,
    scale_pos_weight=scale_pos_weight,
    eval_metric="auc",
    early_stopping_rounds=50,
    random_state=42,
    n_jobs=-1
)

xgb.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    verbose=False
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.85, device=None, early_stopping_rounds=50,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=8, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=-1,
              num_parallel_tree=None, random_state=42, ...)

In [93]:
best_n = xgb.best_iteration + 1

xgb_final = XGBClassifier(
    n_estimators=best_n,
    max_depth=4,
    learning_rate=0.03,
    subsample=0.85,
    colsample_bytree=0.85,
    min_child_weight=8,
    scale_pos_weight=scale_pos_weight,
    eval_metric="auc",
    random_state=42,
    n_jobs=-1
)

xgb_final.fit(X_encoded, y)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=0.85, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric='auc', feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.03, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=4, max_leaves=None,
              min_child_weight=8, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=1000, n_jobs=-1,
              num_parallel_tree=None, random_state=42, ...)

In [94]:
import pandas as pd

imp = pd.Series(
    xgb_final.feature_importances_,
    index=X_encoded.columns
).sort_values()

imp.head(10)

income_level_Upper-Middle       0.000000
income_level_Lower-Middle       0.000000
income_level_Low                0.000000
income_level_High               0.000000
education_level_Postgraduate    0.000000
education_level_No formal       0.000000
education_level_Highschool      0.000000
education_level_Graduate        0.000000
income_level_Middle             0.000000
ethnicity_White                 0.001921
dtype: float32

In [95]:
drop_cols = imp.head(8).index

X_encoded2 = X_encoded.drop(columns=drop_cols)
X_test_encoded2 = X_test_encoded.drop(columns=drop_cols)

In [96]:
from lightgbm import LGBMClassifier, early_stopping

In [97]:
from lightgbm import LGBMClassifier, early_stopping

lgb = LGBMClassifier(
    n_estimators=2000,
    learning_rate=0.03,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

lgb.fit(
    X_tr, y_tr,
    eval_set=[(X_val, y_val)],
    eval_metric="auc",
    callbacks=[early_stopping(stopping_rounds=50)]
)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 349046, number of negative: 210954
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.126512 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1923
[LightGBM] [Info] Number of data points in the train set: 560000, number of used features: 38
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
Training until validation scores don't improve for 50 rounds
Early stopping, best iteration is:
[1686]	valid_0's auc: 0.726705	valid_0's binary_logloss: 0.608233

LGBMClassifier(class_weight='balanced', colsample_bytree=0.8,
               learning_rate=0.03, n_estimators=2000, n_jobs=-1,
               random_state=42, subsample=0.8)

In [98]:
lgb.best_iteration_

1686

In [99]:
best_n = lgb.best_iteration_

lgb_final = LGBMClassifier(
    n_estimators=best_n,
    learning_rate=0.03,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

lgb_final.fit(X_encoded, y)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.074602 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000

LGBMClassifier(class_weight='balanced', colsample_bytree=0.8,
               learning_rate=0.03, n_estimators=1686, n_jobs=-1,
               random_state=42, subsample=0.8)

In [100]:
test_prob = lgb_final.predict_proba(X_test_encoded)[:, 1]

In [101]:
submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

submission.to_csv("submission.csv", index=False)

In [102]:
import pandas as pd

imp = pd.Series(
    lgb_final.feature_importances_,
    index=X_encoded.columns
).sort_values()

In [103]:
drop_cols = imp.head(6).index
drop_cols

Index(['income_level_Upper-Middle', 'income_level_Lower-Middle',
       'income_level_Low', 'income_level_High', 'income_level_Middle',
       'education_level_Postgraduate'],
      dtype='object')

In [104]:
X_enc_red = X_encoded.drop(columns=drop_cols)
X_test_enc_red = X_test_encoded.drop(columns=drop_cols)

In [105]:
lgb_red = LGBMClassifier(
    n_estimators=best_n,
    learning_rate=0.03,
    num_leaves=31,
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

lgb_red.fit(X_enc_red, y)

[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.074876 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000

LGBMClassifier(class_weight='balanced', colsample_bytree=0.8,
               learning_rate=0.03, n_estimators=1686, n_jobs=-1,
               random_state=42, subsample=0.8)

In [106]:
test_prob = lgb_red.predict_proba(X_test_enc_red)[:, 1]

submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

submission.to_csv("submission.csv", index=False)

In [107]:
lgb = LGBMClassifier(
    n_estimators=best_n,
    learning_rate=0.03,
    num_leaves=63,        # 👈 changed
    min_data_in_leaf=50, # 👈 regularization
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

lgb.fit(X_enc_red, y)

[LightGBM] [Warning] min_data_in_leaf is set=50, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=50
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=50, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=50
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.082250 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000

LGBMClassifier(class_weight='balanced', colsample_bytree=0.8,
               learning_rate=0.03, min_data_in_leaf=50, n_estimators=1686,
               n_jobs=-1, num_leaves=63, random_state=42, subsample=0.8)

In [108]:
test_prob_lgb = lgb_red.predict_proba(X_test_enc_red)[:, 1]
test_prob_xgb = xgb_final.predict_proba(X_test_encoded)[:, 1]

test_prob_ensemble = 0.6 * test_prob_lgb + 0.4 * test_prob_xgb

In [109]:
submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob_ensemble
})

submission.to_csv("submission.csv", index=False)

In [110]:
import pandas as pd

imp = pd.Series(
    lgb_final.feature_importances_,
    index=X_encoded.columns
).sort_values()

In [111]:
imp.head(8)

income_level_Upper-Middle       0
income_level_Lower-Middle       0
income_level_Low                0
income_level_High               0
income_level_Middle             0
education_level_Postgraduate    0
education_level_No formal       0
education_level_Highschool      0
dtype: int32

In [112]:
drop_cols = imp.head(6).index

X_enc_pruned = X_encoded.drop(columns=drop_cols)
X_test_enc_pruned = X_test_encoded.drop(columns=drop_cols)

In [113]:
from lightgbm import LGBMClassifier

lgb_pruned = LGBMClassifier(
    n_estimators=best_n,
    learning_rate=0.03,
    num_leaves=63,          # increased
    min_data_in_leaf=80,    # regularization
    subsample=0.8,
    colsample_bytree=0.8,
    class_weight="balanced",
    random_state=42,
    n_jobs=-1
)

lgb_pruned.fit(X_enc_pruned, y)

[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.072541 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000

LGBMClassifier(class_weight='balanced', colsample_bytree=0.8,
               learning_rate=0.03, min_data_in_leaf=80, n_estimators=1686,
               n_jobs=-1, num_leaves=63, random_state=42, subsample=0.8)

In [114]:
test_prob = lgb_pruned.predict_proba(X_test_enc_pruned)[:, 1]

[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80

In [115]:
submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

submission.to_csv("submission.csv", index=False)

In [116]:
import numpy as np
from lightgbm import LGBMClassifier

seeds = [42, 99, 202, 777, 2024]
test_preds = []

for seed in seeds:
    lgb = LGBMClassifier(
        n_estimators=best_n,
        learning_rate=0.03,
        num_leaves=31,
        min_data_in_leaf=80,
        subsample=0.8,
        colsample_bytree=0.8,
        class_weight="balanced",
        random_state=seed,
        n_jobs=-1
    )
    lgb.fit(X_encoded, y)
    test_preds.append(lgb.predict_proba(X_test_encoded)[:, 1])

test_prob = np.mean(test_preds, axis=0)

[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.072642 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.082020 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1921
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing col-wise multi-threading, the overhead of testing was 0.150913 seconds.
You can set `force_col_wise=true` to remove the overhead.
[LightGBM] [Info] Total Bins 1916
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.073579 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1917
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Warning] Found whitespace in feature_names, replace with underlines
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80
[LightGBM] [Info] Number of positive: 436307, number of negative: 263693
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.072568 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 1922
[LightGBM] [Info] Number of data points in the train set: 700000, number of used features: 38
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.500000 -> initscore=0.000000
[LightGBM] [Info] Start training from score 0.000000
[LightGBM] [Warning] min_data_in_leaf is set=80, min_child_samples=20 will be ignored. Current value: min_data_in_leaf=80

In [117]:
from scipy.stats import rankdata

test_prob = rankdata(test_prob) / len(test_prob)

In [118]:
test_prob = test_prob ** 1.05

In [119]:
submission = pd.DataFrame({
    "id": test_ids,
    "diagnosed_diabetes": test_prob
})

submission.to_csv("submission.csv", index=False)